# Site settings
title: 歪歪打正着
SEOTitle: 歪打正着 | TO UR&MY BEST
header-img: img/WechatIMG1088.jpg
email: lastsoulonearth@hotmail.com
description: "正着是谁？"
keyword: "歪歪, 歪歪的Blog, 社会创新，孔歪歪"
url: "http://cannotellwhy.github.io"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/qiubaiying/qiubaiying.github.io.git" # you code repository

# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "迈向高处的挣扎足够填充一个人的心灵，人们应当想象西西弗斯是幸福的。"
sidebar-avatar: /img/10891548509072_.jpg      # use absolute URL, seeing it's used in both `/` and `/about/`



# SNS settings
RSS: false
# weibo_username:    
zhihu_username:     
github_username:   
facebook_username:  
jianshu_username:   
#twitter_username: 




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
gems: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# 评论系统
# Disqus（https://disqus.com/）
# disqus_username: cannotellwhy

# Gitalk
gitalk:
  enable: true    #是否开启Gitalk评论
  clientID: f2c84e7629bb1446c1a4                            #生成的clientID
  clientSecret: ca6d6139d1e1b8c43f8b2e19492ddcac8b322d0d    #生成的clientSecret
  repo: qiubaiying.github.io    #仓库名称
  owner: cannotellwhy    #github用户名
  admin: cannotellwhy
  distractionFreeMode: true #是否启用类似FB的阴影遮罩


# 统计

# Analytics settings
# Baidu Analytics
ba_track_id: b50bf2b12b5338a1845e33832976fd68

# Google Analytics
ga_track_id: 'UA-131795276-1'            # Format: UA-xxxxxx-xx
ga_domain: cannotellwhy.com               # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto


# Comment

<div id="gitmentContainer"></div>
<link rel="stylesheet" href="https://imsun.github.io/gitment/style/default.css">
<script src="https://imsun.github.io/gitment/dist/gitment.browser.js"></script>
<script>
var gitment = new Gitment({
    owner: 'cannotellwhy',
    repo: '_posts',
    oauth: {
        client_id: 'a8effdbf099fa349f0f8',
        client_secret: '8ac5e16c60bcc590813b2b1a5775a105753eba8b',
    },
});
gitment.render('gitmentContainer');
</script>



# Featured Tags
featured-tags: true                     # 是否使用首页标签
featured-condition-size: 1              # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# Friends
friends: [
    {
        title: "waitingformyfriend",
        href: ""
    }
]
